#!/bin/bash

if [[ $1 == "run" ]]; then
  aws dynamodb create-table \
    --table-name Cars \
    --attribute-definitions \
        AttributeName=id,AttributeType=S \
    --key-schema AttributeName=id,KeyType=HASH \
    --table-class STANDARD \
    --billing-mode PAY_PER_REQUEST \
    --endpoint-url http://localhost:8000
    
  aws dynamodb put-item \
    --table-name Cars \
    --item file://Ford.json \
    --return-consumed-capacity TOTAL \
    --endpoint-url http://localhost:8000
    
  aws dynamodb put-item \
    --table-name Cars \
    --item file://Honda.json \
    --return-consumed-capacity TOTAL \
    --endpoint-url http://localhost:8000
    
  aws dynamodb put-item \
    --table-name Cars \
    --item file://GM.json \
    --return-consumed-capacity TOTAL \
    --endpoint-url http://localhost:8000
    
  # aws dynamodb get-item \
  #   --table-name Cars \
  #   --key '{ "make": {"S": "Ford"} }' \
  #   --endpoint-url http://localhost:8000

else
  echo "sets up a local dev environment"
  echo ""
  echo "use dynamo-table-def run to actually run the table creation process"
fi

