version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cars"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1q6155etr3g51"
s3_prefix = "cars"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
