AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  cars api

Globals:
  Function:
    Timeout: 300

Resources:
  # ApiGatewayApi:
  #   Type: AWS::Serverless::Api
  #   Properties:
  #     StageName: Dev
  #     Cors:
  #       AllowMethods: "'GET, POST, OPTIONS'"
  #       AllowOrigin: "'*'"
  #       AllowHeaders: "'Content-type, x-api-key'"
  #       MaxAge: "'86400'"

  CarsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cars/
      Handler: app.handler
      Runtime: nodejs16.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CarsTable
      Architectures:
        - x86_64
      Events:
        CorsPreflightEvent:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: OPTIONS
        GetMakes:
          Type: HttpApi
          Properties:
            Path: /makes
            Method: get
        AddMake:
          Type: HttpApi
          Properties:
            Path: /add-make
            Method: post
        DeleteMake:
          Type: HttpApi
          Properties:
            Path: /delete-make
            Method: get
        GetModels:
          Type: HttpApi
          Properties:
            Path: /models/{make}
            Method: get
        AddModel:
          Type: HttpApi
          Properties:
            Path: /add-model
            Method: post
        UpdateModel:
          Type: HttpApi
          Properties:
            Path: /update-model
            Method: post
        DeleteModel:
          Type: HttpApi
          Properties:
            Path: /delete-model/{make}
            Method: get

  CarsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "cid"
          AttributeType: "S"
        - AttributeName: "make"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "cid"
          KeyType: "HASH"
        - AttributeName: "make"
          KeyType: "RANGE"
      TableName: "Cars"
      BillingMode: PAY_PER_REQUEST
      TableClass: STANDARD

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CarsApi:
    Description: "API Gateway endpoint URL for Prod stage for Cars function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
  CarsFunction:
    Description: "Cars Lambda Function ARN"
    Value: !GetAtt CarsFunction.Arn
  CarsFunctionIamRole:
    Description: "Implicit IAM Role created for Cars function"
    Value: !GetAtt CarsFunctionRole.Arn
  Function:
    Description: "DynamoDB handler function ARN"
    Value: !GetAtt CarsFunction.Arn
