AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  cars api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300

Resources:
  ItemsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: make
        Type: String
      TableName: Cars

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
      # Cors:
      #   AllowMethods: "'GET, POST, OPTIONS'"
      #   AllowHeaders: "'X-Forwarded-For'"
      #   AllowOrigin: "'*'"
      #   MaxAge: "'86400'"
      #   AllowCredentials: true
      Cors:
        AllowMethods: "'GET, POST, OPTIONS'"
        AllowOrigin: "'*'"
        AllowHeaders: "'Content-type, x-api-key'"
        MaxAge: "'86400'"

  CarsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: cars/
      Handler: app.handler
      Runtime: nodejs16.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Cars
      Architectures:
        - x86_64
      Events:
        CorsPreflightEvent:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: OPTIONS
        GetMakes:
          Type: HttpApi
          Properties:
            Path: /makes
            Method: get
        AddMake:
          Type: HttpApi
          Properties:
            Path: /add-make
            Method: post
        DeleteMake:
          Type: HttpApi
          Properties:
            Path: /delete-make
            Method: get
        GetModels:
          Type: HttpApi
          Properties:
            Path: /models/{make}
            Method: get
        AddModel:
          Type: HttpApi
          Properties:
            Path: /add-model
            Method: post
        DeleteModel:
          Type: HttpApi
          Properties:
            Path: /delete-model/{make}
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CarsApi:
    Description: "API Gateway endpoint URL for Prod stage for Cars function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/"
  CarsFunction:
    Description: "Cars Lambda Function ARN"
    Value: !GetAtt CarsFunction.Arn
  CarsFunctionIamRole:
    Description: "Implicit IAM Role created for Cars function"
    Value: !GetAtt CarsFunctionRole.Arn
  Function:
    Description: "DynamoDB handler function ARN"
    Value: !GetAtt DDBHandlerFunction.Arn
