AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  cars api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300

Resources:
  ItemsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: make
        Type: String
      TableName: Cars

  CarsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: cars/
      Handler: app.handler
      Runtime: nodejs16.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Cars
      Architectures:
        - x86_64
      Events:
        GetMakes:
          Type: HttpApi
          Properties:
            Path: /makes
            Method: get
        GetModels:
          Type: HttpApi
          Properties:
            Path: /models/{id}
            Method: get
        DeleteMake:
          Type: HttpApi
          Properties:
            Path: /make/{id}
            Method: delete
        DeleteModel:
          Type: HttpApi
          Properties:
            Path: /model/{makeId}/{modelId}
            Method: delete

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CarsApi:
    Description: "API Gateway endpoint URL for Prod stage for Cars function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/"
  CarsFunction:
    Description: "Cars Lambda Function ARN"
    Value: !GetAtt CarsFunction.Arn
  CarsFunctionIamRole:
    Description: "Implicit IAM Role created for Cars function"
    Value: !GetAtt CarsFunctionRole.Arn
  Function:
    Description: "DynamoDB handler function ARN"
    Value: !GetAtt DDBHandlerFunction.Arn
